### PR TITLE
fix: add ExecutableDefinitions to ignored rules for validation

### PR DESCRIPTION
**Pull request by divyenduz**
1. Add ExecutableDefinitions to ignored rules for schema validation

### CODE REVIEW

**Comment by schickling** [comment]
@asiandrummer can you already merge this one? :shipit: 🤗

**Comment by danez** [comment]
This breaks as it requires now graphql 0.12 at least but the peer dependency still has 0.10 as minimum version.

**Comment by schickling** [comment]
Great point @danez. Unfortunately this wasn't caught by the tests. Do you think it's acceptable to increase the min peer dependency version to 0.12?

**Comment by danez** [comment]
Yes, I updated our project to 0.13 and now it works (still with some workarounds for graphiql as some of its dependencies require 0.12, which means two different versions in our bundles.)

**Pull request merged**
