### PR TITLE
Make watchman dependency optional

### PR DESCRIPTION
**Pull request by mgadda**
This patch, which addresses issue #206, makes watchman an optional dependency of graphql-language-service. The motivation for this patch is defined within the [language server specification](https://microsoft.github.io/language-server-protocol/specification ) under DidChangeWatchedFiles Notification. Less dependencies make for easier administration of IDEs that rely on graphql-language-service. 

That said, it's conceivable that many consumers of this project already rely and/or prefer to use watchman instead of LSP for file watch events. To appease both use cases, **this PR leaves full watchman support intact and functional by default**. Only if watchman is not detected on the system will LSP be used for watched file change events. 

In order to facilitate the two separate mechanisms for being notified of watched file change events, `GraphQLWatchman` has been decoupled from `GraphQLCache`. It is now a _caller_ or consumer of GraphQLCache rather than a dependent class. This means that `GraphQLWatchman.listFiles()` has been replaced by `glob()` when `GraphQLCache` wants to obtain a list of files to parse and cache. 

Watchman subscription is now handled within `MessageProcessor.handleInitializeRequest` and in turn `_subcribeWatchman`. 

Finally, while the diff looks fairly large, it's mostly the same code you already know just moving around a bit.

### CODE REVIEW

**Comment by asiandrummer** [comment]
@mgadda let's add the non-related files as separate PR(s) please.

**Comment by mgadda** [comment]
@asiandrummer if you're referring to my comments about `buildJs.js` and `launch.json`, both of those are removed in the latest revision. So this PR is ready to merge, yes?

**Comment by asiandrummer** [comment]
Thanks @mgadda !

**Comment by asiandrummer** [comment]
@mgadda - apologies again for a huge delay. I'd love to establish a different primary contact mean from emailing - apparently I suck at reading them 😢 
Facebook messenger vs. Slack vs. some other means maybe? Let me know!

**Pull request merged**
