### PR TITLE
Released v1.2

### PR DESCRIPTION
**Pull request by schickling**
## Changes:

- Released #237, #236, #235, #234
- Updated `graphql-config` to `2.0.1`
- Added `graphql` `^0.13.0` as peer dep

### CODE REVIEW

**Comment by lostplan** [comment]
I just want to check… this is just reflecting the changes that are published to npm?

**Comment by schickling** [comment]
Yes. Merging this synchronizes the repo with the state on NPM.

**Comment by lostplan** [comment]
👍

**Comment by IvanGoncharov** [comment]
> Yes. Merging this synchronizes the repo with the state on NPM.

@schickling Having difference beetween `master` and NPM worries me a lot. 
Can you please setup NPM publishing on Travis simular to other `graphql/*` projects. For example:
https://github.com/graphql/graphql-js/blob/ae23c901c5699287c3e870a6fc7d6180049a8eb9/.travis.yml#L41-L48

**Comment by lostplan** [comment]
The (manual) `lerna publish` should update the version numbers, publish to npm, and push to master.

@schickling you can publish to npm but don't have collaborator status on the repo?

**Comment by IvanGoncharov** [comment]
> The (manual) lerna publish should update the version numbers, publish to npm, and push to master.

But you can't create PRs for new releases and that means you can't publish new releases without NPM rights.

So this problem would not exist in a first place if @schickling had an ability to create such PR and have NPM package published after it was merged.

Just sharing my experience with `graphql-js`, `express-graphql`, `graphql-swapi` in all those repos I can do releases without having NPM rights just by committing to master. Plus having releases as PRs is very helpful in preventing incorrect releases, e.g. https://github.com/graphql/graphql-js/pull/1346

**Comment by IvanGoncharov** [comment]
@schickling You forgot update `graphql-language-service-parser` it still `1.1.0`
https://www.npmjs.com/package/graphql-language-service-parser

That forces me to have two different versions of `graphql-config`:
```
$ npm ls graphql-config
dd@1.0.0 /Users/ivang/dev/test
└─┬ graphql-language-service@1.2.0
  ├── graphql-config@2.0.1
  ├─┬ graphql-language-service-interface@1.2.0
  │ ├── graphql-config@2.0.1  deduped
  │ ├─┬ graphql-language-service-parser@1.1.0
  │ │ └── graphql-config@1.1.4
  │ └─┬ graphql-language-service-types@1.2.1
  │   └── graphql-config@2.0.1  deduped
  ├─┬ graphql-language-service-server@1.2.0
  │ └── graphql-config@2.0.1  deduped
  └─┬ graphql-language-service-utils@1.2.1
    └── graphql-config@2.0.1  deduped
```

**Comment by IvanGoncharov** [comment]
@lostplan Don't want to be paranoid but I don't know who else has or will have rights to publish NPM. By having Travis publishing releases I can be sure that package contains the exact same code as `master`.

**Pull request merged**
